# Generated by Django 6.0.1 on 2026-01-29 01:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetterAuthJWK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicKey', models.TextField()),
                ('privateKey', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('expiresAt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'better_auth_jwk',
            },
        ),
        migrations.CreateModel(
            name='BetterAuthVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('identifier', models.TextField()),
                ('expiresAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'better_auth_verification',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('password', models.CharField(blank=True, db_default='', max_length=128)),
                ('name', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('image', models.TextField(blank=True, default=None, null=True, validators=[django.core.validators.URLValidator()])),
                ('ban_reason', models.TextField(blank=True, default=None, null=True)),
                ('role', models.TextField(blank=True, choices=[('user', 'User'), ('admin', 'Admin')], db_default='user')),
                ('banned', models.BooleanField(blank=True, db_default=False, default=False, null=True)),
                ('ban_expires', models.DateTimeField(blank=True, default=None, help_text="The date when the user's ban will expire.", null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('street_address', models.CharField(max_length=255)),
                ('pin_code', models.DecimalField(decimal_places=0, max_digits=12)),
                ('primary', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BetterAuthAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountId', models.TextField()),
                ('providerId', models.TextField()),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('scope', models.TextField(blank=True, default=None, null=True)),
                ('password', models.TextField(blank=True, default=None, null=True)),
                ('idToken', models.TextField(blank=True, default=None, null=True)),
                ('accessToken', models.TextField(blank=True, default=None, null=True)),
                ('refreshToken', models.TextField(blank=True, default=None, null=True)),
                ('accessTokenExpiresAt', models.DateTimeField(blank=True, default=None, null=True)),
                ('refreshTokenExpiresAt', models.DateTimeField(blank=True, default=None, null=True)),
                ('user', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'better_auth_account',
            },
        ),
        migrations.CreateModel(
            name='BetterAuthSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('expiresAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('userAgent', models.TextField(blank=True, default=None, null=True)),
                ('ipAddress', models.TextField(blank=True, default=None, null=True)),
                ('impersonatedBy', models.TextField(blank=True, default=None, null=True)),
                ('user', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'better_auth_session',
            },
        ),
    ]
